sylius_grid:
    grids:
        app_user:
            limits: [25, 50, 100, 250, 500]
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.user.class%"
            fields:
                id:
                    type: twig
                    label: app.admin.ui.id
                    sortable: ~
                    options:
                        template: '@auth/admin/user/link-to-show.html.twig'
                createdAt:
                    type: datetime
                    label: app.admin.ui.modules.auth.user.properties.created_at
                    sortable: ~
                email:
                    type: string
                    label: app.admin.ui.modules.auth.user.properties.email
                    sortable: ~
                name:
                    type: string
                    label: app.admin.ui.modules.auth.user.properties.name
                    sortable: ~
            sorting:
                id: desc
            filters:
                id:
                    type: int
                    form_options:
                        label: app.admin.ui.modules.auth.user.properties.id
                        type: equal
                    options:
                        type: equal
                name:
                    type: like
                    form_options:
                        field_name: name
                        label: app.admin.ui.modules.auth.user.properties.name
                email:
                    type: like
                    form_options:
                        field_name: email
                        label: app.admin.ui.modules.auth.user.properties.email
            actions:
                main:
                    create:
                        type: create
