liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
