---
- name: Update and install dependencies for Docker
  become: true
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Create directory for Docker keyrings
  become: true
  file:
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  vars:
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }

- name: Update packages list again
  become: true
  apt:
    update_cache: yes

#- name: Set permissions for Docker GPG key
#  become: true
#  file:
#    path: /etc/apt/keyrings/docker.gpg
#    mode: '0644'

-   name: Set periodic Docker prune
    cron:
        name: docker-prune
        job: 'docker system prune -af --filter "until=$((30*24))h"'
        minute: '0'
        hour: '1'

- name: Install Docker and related tools
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Create Docker network
  become: true
  docker_network:
    name: app-network
