services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Auth\Infrastructure\Security\JWT:
        public: true

    App\Auth\Infrastructure\Security\JwtTokenizer:
        public: true
