services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                name: doctrine.event_subscriber
                connection: default

    App\Auth\:
        resource: '%kernel.project_dir%/src/Auth/'
        exclude:
            - '../Resource'

    App\Auth\Entry\Http\:
        resource: '%kernel.project_dir%/src/Auth/Entry/Http/'
        tags: [ 'controller.service_arguments' ]

    Symfony\Component\Security\Core\User\UserProviderInterface:
        class: App\Auth\Infrastructure\Security\UserProvider
