sylius_grid:
    grids:
        app_proxy_checker_proxy:
            limits:
                - 25
                - 50
                - 100
                - 250
                - 500
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.proxy_checker.proxy.class%'
            fields:
                id:
                    type: twig
                    label: app.admin.ui.id
                    options:
                        template: '@proxyChecker/admin/proxy/link-to-show.html.twig'
                    sortable: ~
                createdAt:
                    type: datetime
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.created_at
                    sortable: ~
                updatedAt:
                    type: datetime
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.updated_at
                    sortable: ~
                ipProxy:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.ip_proxy
                    sortable: ~
                ipReal:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.ip_real
                    sortable: ~
                port:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.port
                    sortable: ~
                proxyType:
                    type: twig
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.proxy_type
                    options:
                        template: '@proxyChecker/admin/proxy/enum/proxyType.html.twig'
                    sortable: ~
                proxyStatus:
                    type: twig
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.proxy_status
                    options:
                        template: '@proxyChecker/admin/proxy/enum/proxyStatus.html.twig'
                    sortable: ~
                country:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.country
                    sortable: ~
                region:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.region
                    sortable: ~
                city:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.city
                    sortable: ~
                timeout:
                    type: string
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.timeout
                    sortable: ~
                checkList:
                    type: twig
                    label: app.admin.ui.show_proxy_checker.check_list
                    options:
                        template: '@proxyChecker/admin/check_list/link-to-show.html.twig'
                    sortable: ~
            sorting:
                id: desc
            filters:
                id:
                    type: int
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.id
                    form_options:
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.id
                        type: equal
                    options:
                        type: equal
                ipProxy:
                    type: like
                    form_options:
                        field_name: ipProxy
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.ip_proxy
                ipReal:
                    type: like
                    form_options:
                        field_name: ipReal
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.ip_real
                port:
                    type: int
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.port
                    form_options:
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.port
                        type: equal
                    options:
                        type: equal
                proxyType:
                    type: select
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.proxy_type
                    form_options:
                        choices:
                            app.admin.ui.modules.proxy_checker.proxy.enums.proxy_type.http: http
                            app.admin.ui.modules.proxy_checker.proxy.enums.proxy_type.socks: socks
                            app.admin.ui.modules.proxy_checker.proxy.enums.proxy_type.other: other
                proxyStatus:
                    type: select
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.proxy_status
                    form_options:
                        choices:
                            app.admin.ui.modules.proxy_checker.proxy.enums.proxy_status.work: work
                            app.admin.ui.modules.proxy_checker.proxy.enums.proxy_status.not_work: not_work
                country:
                    type: like
                    form_options:
                        field_name: country
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.country
                region:
                    type: like
                    form_options:
                        field_name: region
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.region
                city:
                    type: like
                    form_options:
                        field_name: city
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.city
                timeout:
                    type: int
                    label: app.admin.ui.modules.proxy_checker.proxy.properties.timeout
                    form_options:
                        label: app.admin.ui.modules.proxy_checker.proxy.properties.timeout
                        type: equal
                    options:
                        type: equal
                checkList:
                    type: autocomplete
                    form_options:
                        field_name: checkList
                        label: app.admin.ui.modules.proxy_checker.proxy.relations.check_list
                        suggester: proxy_checker_check_list
            actions:
                main:
#                    create:
#                        type: create
